# Generated by Django 4.2.28 on 2026-02-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0004_classgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.stage')),
            ],
            options={
                'ordering': ['stage', 'day', 'start_time'],
                'unique_together': {('stage', 'day', 'start_time', 'end_time')},
            },
        ),
    ]
